#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

STRING="Hello World!"
CECI="Ceci n\x27est pas une page"

FILE="/etc/nginx/sites-available/default"
ERRORFILE="/var/www/html/error.html"

CONFIGFILE=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
                add_header X-Served-By \$hostname;
        }
        location /redirect_me {
                return 301 https://youtube.com/watch?v=QH2-TGUlwu4;
        }
        error_page 404 /error.html;
        location = /error.html {
                root /var/www/html/;
                internal;
                add_header X-Served-By \$hostname;
        }
}"

bash -c "echo -e '$CONFIGFILE' > /etc/nginx/sites-enabled/default"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "$STRING" > /var/www/html/index.nginx-debian.html

echo -e "$CECI" > "$ERRORFILE"

service nginx restart
