#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
# Enables management via the init script.
# Distributes requests using a round-robin algorithm.

BACKEND="\nbackend web_back\n\tbalance roundrobin\n\tserver 43916-web-01 52.3.245.92:80 check\n\tserver 43916-web-02 54.210.58.167:80 check\n"
FRONTEND="\nfrontend web_front\n\tbind *:80\n\tdefault_backend web_back\n"
HAPROXY_CONFIG_PATH="/etc/haproxy/haproxy.cfg"
HAPROXY_DEFAULTS_FILE="/etc/default/haproxy"

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update
apt-get install -y haproxy

chmod 646 "$HAPROXY_CONFIG_PATH" "$HAPROXY_DEFAULTS_FILE"
echo -e "ENABLED=1" >> "$HAPROXY_DEFAULTS_FILE"
echo -e "$FRONTEND" >> "$HAPROXY_CONFIG_PATH"
echo -e "$BACKEND" >> "$HAPROXY_CONFIG_PATH"
chmod 644 "$HAPROXY_CONFIG_PATH" "$HAPROXY_DEFAULTS_FILE"

service haproxy start
