#!/usr/bin/env bash
#Displays thr time for 12hours and 59mins

hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    mins=1
    while [ $mins -le 59 ]
    do
	echo "$mins"
	mins=$(( mins + 1 ))
    done
    hour=$(( hour + 1 ))
done
